// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6IOk1pmwqqZq-ZI9tpTSnV61BCGMcB54',
    appId: '1:592350788744:web:f4888b11554e1ba82cf33d',
    messagingSenderId: '592350788744',
    projectId: 'coletotal-32735',
    authDomain: 'coletotal-32735.firebaseapp.com',
    databaseURL: 'https://coletotal-32735-default-rtdb.firebaseio.com',
    storageBucket: 'coletotal-32735.firebasestorage.app',
    measurementId: 'G-K74F8J411S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0BH82EqVl88FEn2AyiT3ACaev--VPo6o',
    appId: '1:592350788744:android:be23bf46df07b83f2cf33d',
    messagingSenderId: '592350788744',
    projectId: 'coletotal-32735',
    databaseURL: 'https://coletotal-32735-default-rtdb.firebaseio.com',
    storageBucket: 'coletotal-32735.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXhSKo4x8PJgWvM93pjYjkOLMS17RwX5I',
    appId: '1:592350788744:ios:8bf91677c6ccaa5b2cf33d',
    messagingSenderId: '592350788744',
    projectId: 'coletotal-32735',
    databaseURL: 'https://coletotal-32735-default-rtdb.firebaseio.com',
    storageBucket: 'coletotal-32735.firebasestorage.app',
    iosBundleId: 'com.example.taxi1',
  );
}
